// IMPORTS
import express from "express";
import { Server } from "socket.io";
import mongoose from "mongoose";
import dotenv from "dotenv";
import morgan from "morgan";
import http from "http";
import cors from "cors";
import rateLimit from "express-rate-limit";

import { json } from "body-parser";
import cookieParser from "cookie-parser";
import { router } from "./routers/userRouter";
import msgRouter from "./routers/msgRouter";
import conversationRouter from "./routers/conRouter";
import globalErrorHandler from "./controller/errorController";

// ###########################################################
// Initialize Express app
dotenv.config({ path: "./.env" });
const app = express();
app.use(json());
app.use(cors({ origin: "http://localhost:3000", credentials: true }));
app.options("*", cors());

// Limit requests from same API
const limiter = rateLimit({
  max: 100,
  windowMs: 60 * 60 * 1000,
  message: "Too many requests from this IP, please try again in an hour!",
});
app.use("/api", limiter);

app.use(globalErrorHandler);
// ###########################################################
// Socket IO server
const server = http.createServer(app);

const io = new Server(server, {
  cors: {
    origin: "http://localhost:3000",
    methods: ["GET", "POST"],
    credentials: true,
  },
});

// The socket.id is generated by the server when a client establishes a connection.
io.on("connection", (socket) => {
  console.log(`Connection ID: ${socket.id}`);

  socket.on("send_message", (data) => {
    // Emit the "receive_message" event to all connected clients
    io.emit("receive_message", data);
    console.log(data);
  });

  socket.on("disconnect", () => {
    console.log("Disconnected", socket.id);
  });
});
// ##############################################################

// Development logging
if (process.env.NODE_ENV === "development") {
  app.use(morgan("dev"));
}
app.use(cookieParser());
// ROUTES
app.use("/api/v1/users", router);
app.use("/api/v1/msgs", msgRouter);
app.use("/api/v1", conversationRouter);
// ##############################################################
// DATABASE CONNECTION
const DB = process.env.DATABASE.replace(
  "<PASSWORD>",
  process.env.DATABASE_PASSWORD
);

mongoose.connect(DB).then(() => console.log("DB Connection Successful!"));
// ##############################################################

//SERVER RUNNING
const port = process.env.PORT || 8000;
server.listen(port, () => {
  console.log(`APP RUNNING ON PORT ${port}...`);
});
